version: '3'
services:
  database:
    image: postgres:12-alpine
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    environment:
      - SPROCKETS_CACHE=/cache
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/kopi-tracker
      - gem_cache:/usr/local/bundle/gems
      - cache:/cache
      - node_modules:/kopi-tracker/node_modules
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      - database
    environment:
      RAILS_ENV: development
volumes:
  gem_cache:
  db_data:
  node_modules:
  cache:
